# Generated by Django 6.0.2 on 2026-02-15 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('rank', models.CharField(max_length=50, verbose_name='Grado (Dan)')),
                ('bio', models.TextField(verbose_name='Biografía')),
                ('photo', models.ImageField(blank=True, upload_to='instructors/', verbose_name='Foto Perfil')),
                ('is_director', models.BooleanField(default=False, verbose_name='¿Es Director?')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Sede')),
                ('address', models.CharField(max_length=200, verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('google_maps_url', models.URLField(blank=True, verbose_name='Link Google Maps')),
                ('photo', models.ImageField(blank=True, upload_to='locations/', verbose_name='Foto Sede')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titular')),
                ('slug', models.SlugField(help_text='Identificador para la URL (ej: torneo-navidad-2024)', unique=True)),
                ('content', models.TextField(verbose_name='Contenido')),
                ('image', models.ImageField(blank=True, upload_to='news/', verbose_name='Imagen Principal')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Publicación')),
            ],
            options={
                'verbose_name_plural': 'Noticias',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Empresa')),
                ('logo', models.ImageField(upload_to='sponsors/', verbose_name='Logo')),
                ('website', models.URLField(blank=True, verbose_name='Web del Patrocinador')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visible')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Evento')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('start_date', models.DateTimeField(verbose_name='Fecha Inicio')),
                ('end_date', models.DateTimeField(verbose_name='Fecha Fin')),
                ('registration_link', models.URLField(blank=True, verbose_name='Link Inscripción')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='club.location', verbose_name='Sede')),
            ],
        ),
    ]
