# Generated by Django 6.0.2 on 2026-02-15 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'Noticias'},
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='is_director',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.AddField(
            model_name='news',
            name='img1',
            field=models.ImageField(default='https://media.tacdn.com/media/attractions-splice-spp-674x446/07/b7/3e/96.jpg', upload_to='news/', verbose_name='Imagen 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Imagen 2'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Lugar/Localización'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='¿Activo?'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='website',
            field=models.URLField(blank=True, verbose_name='URL Web'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_range', models.CharField(max_length=50, verbose_name='Rango de Edad (ej: 6-12 años)')),
                ('schedule', models.CharField(max_length=100, verbose_name='Horario (ej: L-X 17:00)')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='club.instructor', verbose_name='Instructor')),
                ('locations', models.ManyToManyField(related_name='groups', to='club.location', verbose_name='Sedes donde se imparte')),
            ],
        ),
    ]
