# Generated by Django 5.2.11 on 2026-03-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_news_options_remove_instructor_is_director_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Documento')),
                ('file', models.FileField(upload_to='chat_documents/', verbose_name='Archivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Metadatos (Colección, etc.)')),
            ],
            options={
                'verbose_name': 'Documento de RAG',
                'verbose_name_plural': 'Documentos de RAG',
            },
        ),
        migrations.CreateModel(
            name='ChatQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_question', models.TextField(verbose_name='Pregunta del Usuario')),
                ('bot_response', models.TextField(verbose_name='Respuesta del Bot')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Metadatos Extra')),
            ],
            options={
                'verbose_name': 'Consulta de Chatbot',
                'verbose_name_plural': 'Consultas de Chatbot',
            },
        ),
    ]
